version: 2

jobs:
  omnibus_osx_llvm:
    macos:
      xcode: 13.4.1
    environment:
      MACOSX_DEPLOYMENT_TARGET: 10.11
    shell: /bin/bash --login -eo pipefail
    steps:
      - run:
          name: Setup environment
          command: |
            brew unlink python@2 || true

            brew update
            # We need ruby-install >= 0.8.3
            brew install ruby-install

            ruby-install ruby 2.7.3

            brew install pkgconfig libtool cmake

            sudo mkdir -p /opt/llvm
            sudo chown $(whoami) /opt/llvm/
            sudo mkdir -p /var/cache
            sudo chown $(whoami) /var/cache
      - checkout
      - run:
          no_output_timeout: 280m
          name: Build LLVM
          command: |
            cd omnibus
            bundle check || bundle install --binstubs
            bundle exec omnibus build llvm
      - store_artifacts:
          path: ./omnibus/pkg
          destination: llvm

workflows:
  version: 2

  build_llvm:
    jobs:
      - omnibus_osx_llvm:
          filters:
            branches:
              only:
                - /.*\bbuild-llvm\b.*/
